name: Deployment

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    if: github.actor!= 'dependabot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '18'
      - name: Get version in pom.xml
        id: get_version
        run: echo ::set-output name=VERSION::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      - name: Build with Maven
        run: ./mvnw -B clean install --file pom.xml -P makeRelease
      - name: Archive jar in artifacts
        uses: actions/upload-artifact@v3
        with:
          name: core
          path: |
            ${{ github.workspace }}/target/core-${{ steps.get_version.outputs.VERSION }}-exec.jar
