name: Deployment

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    if: github.actor!= 'dependabot'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      pull-requests: 'write'
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '18'
      - name: Get version in pom.xml
        id: get_version
        run: echo ::set-output name=VERSION::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      - name: Build with Maven
        run: ./mvnw -B clean install --file pom.xml -P makeRelease
      - id: auth_google
        name: Login to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - id: upload_artifact
        name: Upload jar in Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v0
        with:
          path: '${{ github.workspace }}/target/core-${{ steps.get_version.outputs.VERSION }}-exec.jar'
          destination: 'les-sagas-mp3-build/api-review-${{ github.event.number }}'
      - name: Get subnetwork CIDR
        id: get_subnetwork_cidr
        run: echo ::set-output name=CIDR::10.2.$(expr ${{ github.event.number }} % 255).0/24
      - name: Start Google Cloud Build trigger
        run: |
          curl --location --request POST 'https://content-cloudbuild.googleapis.com/v1/projects/les-sagas-mp3/triggers/e58d3067-a969-4a79-87ac-7e28b1fc53dc:run' \
            --header 'Authorization: Bearer ${{ steps.auth_google.outputs.access_token }}' \
            --header 'Content-Type: application/json' \
              --data-raw '{
            "substitutions": {
              "_API_ARCHIVE_URL": "https://storage.cloud.google.com/les-sagas-mp3-build/${{ steps.upload_artifact.outputs.uploaded }}",
              "_API_VERSION": "${{ steps.get_version.outputs.VERSION }}",
              "_ENVIRONMENT_NAME": "review-api-${{ github.event.number }}",
              "_ENVIRONMENT_TEMPLATE": "review-api",
              "_SUBNETWORK_CIDR": "${{ steps.get_subnetwork_cidr.outputs.CIDR }}",
            }
            }'
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Artifact has been uploaded to the following location : 
            https://storage.cloud.google.com/les-sagas-mp3-build/${{ steps.upload_artifact.outputs.uploaded }}
            
            The deployment to the following environment has begun. It will be available there :
            https://app-review-api-${{ github.event.number }}.les-sagas-mp3.fr
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
