name: Release

on:
  push:
    branches: [ master ]

jobs:

  verify-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
      - name: Get version in pom.xml
        id: get_version
        run: echo "VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
      - name: Test snapshot
        run: if [[ "${{ steps.get_version.outputs.VERSION }}" == *"-SNAPSHOT" ]]; then exit 1; else exit 0; fi
      - name: Get release
        id: get_release
        run: echo "RELEASE_HTTP_CODE=$(curl -s -o out.html -w '%{http_code}'  https://github.com/les-sagas-mp3/core/releases/tag/${{ steps.get_version.outputs.VERSION }};)" >> $GITHUB_OUTPUT
      - name: Test release existence
        run: if [[ "${{ steps.get_release.outputs.RELEASE_HTTP_CODE }}" -eq "200" ]]; then exit 1; else exit 0; fi

  build:
    needs: verify-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
      - name: Build with Maven
        run: ./mvnw -B clean install spring-boot:build-image --file pom.xml

  release:
    needs: [ verify-version, build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Config Git
        run: git config user.email "${{ secrets.GIT_CONFIG_EMAIL }}" && git config user.name "${{ secrets.GIT_CONFIG_NAME }}"
      - run: git tag ${{ needs.verify-version.outputs.version }}
      - run: git push origin ${{ needs.verify-version.outputs.version }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
      - name: Build with Maven
        run: ./mvnw -B clean install --file pom.xml -P makeRelease
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ needs.verify-version.outputs.version }}
          tag_name: ${{ needs.verify-version.outputs.version }}
          draft: false
          prerelease: false
          files: ${{ github.workspace }}/target/core-${{ needs.verify-version.outputs.version }}-exec.jar

  publish-maven:
    needs: [ verify-version, release ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '${{ needs.verify-version.outputs.version }}'
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
      - name: Publish package
        run: mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-docker:
    needs: [ verify-version, release ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: '${{ needs.verify-version.outputs.version }}'
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
      - name: Build with Maven
        run: ./mvnw -B clean spring-boot:build-image --file pom.xml
      - name: Get version in pom.xml
        id: get_version
        run: echo "VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
      - name: Tag the version image for Docker Hub
        run: docker tag core:${{ steps.get_version.outputs.VERSION }} lessagasmp3/api:${{ steps.get_version.outputs.VERSION }}
      - name: Tag the latest image for Docker Hub
        run: docker tag core:${{ steps.get_version.outputs.VERSION }} lessagasmp3/api:latest
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish latest to Docker Hub
        run: docker push lessagasmp3/api:latest
      - name: Publish version to Docker Hub
        run: docker push lessagasmp3/api:${{ steps.get_version.outputs.VERSION }}

  deploy-production:
    needs: [ verify-version, release ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: les-sagas-mp3/infrastructure
          token: ${{ secrets.PUSH_DEFAULT_VERSIONS_GITHUB_TOKEN }}
          path: infrastructure
      - name: Replace API version
        run: sed -i -r "s/api_version = \".*\"/api_version = \"${{ needs.verify-version.outputs.version }}\"/g" infrastructure/terraform/environments/default_versions.tfvars
      - name: Push new default version
        run: |
          cd infrastructure
          git config user.email "${{ secrets.GIT_CONFIG_EMAIL }}" && git config user.name "${{ secrets.GIT_CONFIG_NAME }}"
          git status
          git add .
          git commit --allow-empty -m "Release API '${{ steps.get_version.outputs.VERSION }}'"
          git push